# build
# deploy to Azure as App service

name: Build Deploy TiobeIndex Blazor App

env:
  AZURE_WEBAPP_NAME: tiobeindex-gc                  # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: 'publish'              # set this to the path to your web app project

on:
  workflow_dispatch:                                # manually triggered
jobs:
  build_deploy:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build for Release
      run: dotnet build --configuration Release

    - name: Publish web app
      run: dotnet publish -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp' 
      
    # Deploy to Azure Web app
    - name: Run Azure webapp deploy action using publish profile credentials
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }}                        # e.g. tiobeindex-gc
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }} # Define secret variable in repository settings as per action documentation
        package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'
    
    